ReadOnlySet를 작성합니다.
sang-hyeon/Java-ReadonlyCollections pull request #18
Opened 2022-11-11 05:13 UTC by abbyinkr

* convert_to_runtime_readonly_set 테스트케이스만 작성했습니다.
  다른 테스트케이스들은 GeneralReadOnlyCollectionTest에서 검증되었다고 생각하여 생략했습니다.

2022-11-11 05:23 UTC, sang-hyeon commented
> issue에 작성하신 ReadOnlySet의 T get(int index)는 생략했습니다.
Set은 인덱스로 데이터에 접근할수 없어서 필요없다고 생각했습니다!

좋은 의견입니다. 

말씀해주신 것처럼 Java의 'Set'에서는 index를 통한 get을 지원하지 않습니다.

그런데 index를 통한 get이 사용성이 있다고 생각하여 향후 추가를 고민해보는게 어떨지... 싶네요.  이 사항은 새 이슈로 만들어두어야겠습니다.

2022-11-11 05:25 UTC, sang-hyeon requested changes

2022-11-11 05:25 UTC, sang-hyeon commented on readonlycoll/src/main/java/readonlycollections/GeneralReadOnlySet.java
> +public class GeneralReadOnlySet<T> implements ReadOnlySet<T> {
GeneralReadOnlyCollection을 상속받아 처리하는게 어떨까요?

'GeneralReadOnlyList<>'를 참고하면 어떤 의미인지 알 수 있습니다.

2022-11-11 05:41 UTC, sang-hyeon commented
Readme에 readonlySet 추가좀

2022-11-11 07:12 UTC, abbyinkr commented on readonlycoll/src/main/java/readonlycollections/GeneralReadOnlySet.java
> +public class GeneralReadOnlySet<T> implements ReadOnlySet<T> {
옙

2022-11-11 07:19 UTC, sang-hyeon requested changes

2022-11-11 07:19 UTC, sang-hyeon commented on readonlycoll/src/main/java/readonlycollections/GeneralReadOnlySet.java
> +
`GeneralReadOnlyCollection<>`을 상속받으면 가지고 있는 기능을 물려받기에 이 구현은 필요가 없는거 같아요.

뭔가 달라지는게 있다면 @override로 재정의 할 수 있지만 할게 없는거 같은데 어떻게 보시나요?

2022-11-14 01:41 UTC, abbyinkr commented on readonlycoll/src/main/java/readonlycollections/GeneralReadOnlySet.java
> +
그러네요 이 부분은 제가 미처 체크 못했어요!

2022-11-14 05:43 UTC, abbyinkr reviewed
수정합니다.

2022-11-14 13:10 UTC, sang-hyeon approved these changes

2022-11-14 13:12 UTC, merged