Introduce ReadOnlyQueue<>.
sang-hyeon/Java-ReadonlyCollections pull request #22
Opened 2022-11-13 13:26 UTC by sang-hyeon

2022-11-14 02:20 UTC, abbyinkr commented on readonlycoll/src/main/java/readonlycollections/GeneralReadOnlyQueue.java
> +    public T dequeue() throws NoSuchElementException {
큐의 마지막 요소를 반환하고 그 요소를 제거하는 함수인데 함수명 dequeue에서 de- 는 부정의 의미로 쓰인건가요? 제가 잘 이해한지 모르겠어요.

2022-11-14 02:26 UTC, abbyinkr requested changes

2022-11-14 02:26 UTC, abbyinkr commented on readonlycoll/src/main/java/readonlycollections/GeneralReadOnlyQueue.java
> +    public T dequeue() throws NoSuchElementException {
큐의 마지막 요소를 반환하고 그 요소를 제거하는 함수인데 함수명 dequeue에서 de- 는 부정의 의미로 쓰인건가요? 제가 잘 이해한지 모르겠어요.

2022-11-14 02:26 UTC, abbyinkr commented on readonlycoll/src/main/java/readonlycollections/GeneralReadOnlyQueue.java
> +    public Optional<T> tryDequeue() {
요것도 좀 헷갈리네요. getFirstOfQueue..?

2022-11-14 13:08 UTC, sang-hyeon commented on readonlycoll/src/main/java/readonlycollections/GeneralReadOnlyQueue.java
> +    public T dequeue() throws NoSuchElementException {
적절한 이름을 찾았는데, 레퍼런스로 삼고 있는 [Microsoft docs](https://learn.microsoft.com/ko-kr/dotnet/api/system.collections.queue.dequeue?view=net-7.0)를 참고했어요!

2022-11-14 13:09 UTC, sang-hyeon commented on readonlycoll/src/main/java/readonlycollections/GeneralReadOnlyQueue.java
> +    public Optional<T> tryDequeue() {
우선 Optional은 get을 시도하고 불가능할 때 empty를 반환해요. 그래서 try라는 이름이 적절한데, 거기서 Dequeue를 붙였습니다! 좀 이상할까요?

2022-11-15 08:58 UTC, abbyinkr approved these changes

2022-11-15 13:22 UTC, merged